YUI.add('srpl-lib-templates', function(Y){
// DO NOT EDIT THIS FILE
// this should be automatically generated by using the .*.html files in templates
Y.namespace('srpl.Lib');
Y.srpl.Lib.templates = {
    pagination:Y.template('<div class="pagination">\n	Results <%= start %> to <%= end %> of <%= total %>\n	<ul>\n		<% if(previous) { %>\n		<li>\n			<button title="Previous" type="button" class="noborder previous"><span>Prev</span></button>\n		</li>\n		<%\n		}\n		for(var i=navStart;i<(navStart + navCount);i++) {\n		%>\n		<li>\n			<button title="<%= i %>" type="button" data-paginate="<%=i%>" class="noborder paginate <%= (i===selected) ? \'active\' : \'\' %>" <%= (i===selected) ? \'disabled=""\' : \'\' %>>\n				<%= i %>\n			</button>\n		</li>\n		<%\n		}\n		if(next) {\n		%>\n		<li>\n			<button title="Next" type="button" class="noborder next"><span>Next</span></button>\n		</li>\n		<% } %>\n	</ul>\n</div>')
};
}, '@VERSION@',{
    // [bug 5892107] no need to require assets     
    requires:['srpl-template']
});