YUI.add('srpl-foursquare-templates', function(Y){
// DO NOT EDIT THIS FILE
// this should be automatically generated by using the .*.html files in templates
Y.namespace('srpl.Foursquare');
Y.srpl.Foursquare.templates = {
    base:Y.template('<div class="srpl-container-header">\n    <h5>Tips of Foursquare</h5>\n</div>\n<div class="srpl-container-body">\n    <ul>\n        <li>"... at bar. Ask that the cheece cart be brough round. Do what comes naturally." <span class="tips">(7 tips)</span></li>\n        <li>"Try the Lobster Risotto - It\'s like amazing (via @Foodspotting)" <span class="tips">(3 tips)</span></li>\n        <li>"... cheese cart, great wine list, great atmosphere, great service (best I\'ve..." <span class="tips">(5 tips)</span></li>\n    </ul>\n    <ul class="srpl-actions clearfix">\n        <li class="first-child">\n            <a href="#" title="Read all 77 tips on Foursquare">Read all 77 tips on Foursquare</a>\n        </li>\n    </ul>\n</div>')
};
}, '@VERSION@',{
    // [bug 5892107] no need to require assets     
    requires:['srpl-template']
});