YUI.add('srpl-search-templates', function(Y){
// DO NOT EDIT THIS FILE
// this should be automatically generated by using the .*.html files in templates
Y.namespace('srpl.Search');
Y.srpl.Search.templates = {
    location:Y.template('<div data-obd="<%= (location.raw.obd) %>" class="location <%= location.raw.type  %>">\n    <% if (location.raw.type === "current" || location.raw.type === "default") { %>\n        <span class="<%= (location.raw.type === "current")? \'current-icon\' : \'default-icon\' %>"></span>\n    <% } %>\n    <span><%= (location.raw.lbl)? location.display.replace(\'(\', \'<span class="labelled-location">(\').replace(\')\', \')</span>\') : location.display %><%= (location.raw.type === "current")? \' <span class="info-text">(current location)</span>\' : (location.raw.type === "default")? \' <span class="info-text">(default location)</span>\' : \'\'%></span>\n</div>'),
		manageLink:Y.template('<div class="manage">\n    <a href="<%= manageLink %>" target="_blank">\n        <span class="manage-icon"></span><span class="linkText">Manage Locations</span>\n    </a>\n</div>'),
		noDefaultLocation:Y.template('<div class="location default icon-spacing no-location">\n    <a href="<%= manageLink %>" target="_blank">\n    	<span class="default-icon"></span> \n        <span class="link-text"><%= noDefaultLocationText %> <span class="info-text">(edit)</span> </span>\n    </a>\n</div>')
};
}, '@VERSION@',{
    // [bug 5892107] no need to require assets     
    requires:['srpl-template']
});